apiVersion: v1
kind: Pod
metadata: 
  name: simple-nginx
  namespace: roboshop
  labels:
    - name: simple-project

spec:
  containers:
    - name: simple-ngonx
      image: nginx
      ports:
        - containerPort: 80
  