apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-env
  namespace: roboshop
  labels:
    department: production
spec:
  containers:
    - name: nginx-env
      image: nginx:latest
      imagePullPolicy: always
      ports:
        - containerPort: 80
      env:
        - name: username
          value: kumara
        - name: job
          value: devops
