apiVersion: v1
kind: Pod
metadata:
  name: sample-nginx-configmap
  namespace: roboshop
  labels:
    production: "yes"
    team: "testing"
spec:
    containers:
      - name: nginx
        image: nginx:alpine
        ports:
          - containerPort: 80
            name: http-web-services
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
        env:
          - name: database
            valueFrom:
              configMapKeyRef:
                name: cource-config
                key: databasu_url
          - name: ipaddress
            valueFrom:
              configMapKeyRef:
                name: cource-config
                key: api-server-ip

---
apiVersion: v1
kind: Service
metadata:
  name: service-pod
spec:
  selector:
    production: "yes"
    team: "testing"
  ports:
    - name: service-port
      ports: 80
      targetPort: http-web-services