apiVersion: v1
kind: Pod
metadata:
  name: configmapRef-pod
  namespace: roboshop
spec:
  containers:
    - name: nginx1
      image: nginx:latest
      envFrom:
        - configMapRef:
            name: cource-config