apiVersion: v1
kind: Secret
metadata:
  name: pod-secret
data:
  name: UmFqYQo=
  password: UmFqYUAxMjMK

---

apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: nginx123
      image: nginx:latest
      envFrom:
        - secretRef:
            name: pod-secret

