apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replica
  labels:
    name: nginx-replica
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-nginx
  template:
    metadata:
      app: web-nginx
    spec:
      containers:
        - name: nginx-web
          image: nginx:latest
          ports:
            - containerPort: 80