apiVersion: apps/v1
kind: ReplicaSet
matadata:
  name: frontend-replica
  labels:
    app: nginx-replica

spec:
  replicas: 3
  selectors:
    matchLabels:
      app: nginx
template:
  metadata:
    labels:
      app: nginx
    spec:
      containers:
        name: nginx-frontend
        imeage: nginx:latest
        ports:
        - containerPort: 80  