apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  labels:
    name: nginx-deployment
spec:
  replicaset: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      name: nginx-deployment
      image: nginx:latest
      ports:
        - containerPort: 80
