apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  labels:
    name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-deployment
          image: nginx:1.24.0
          ports:
          - containerPort: 80
