apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
  namespace: roboshop
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-deploy
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
          - containerPort: 80
          
