apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: roboshop
  labels:
    team: "testing"
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
      - containerPort: 80
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "250m"
          memory: "256Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: node-port
  namespace: roboshop
spec:
  type: NodePort
  selector:
      team: "testing"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007

