apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: roboshop
  labels:
    env: production
    project: roboshop
  
spec:
  containers:
    - name: nginx-prod
      image: nginx:latest
      ports:
        - containerPort: 80