apiVersion: v1
kind: Pod
metadata:
  name: nginx-confidmap
spec:
  containers:
    - name: nginx
      image: nginx
      env:
      - name: course
        valueFrom:
          configMapKeyRef:
            name: course-config
            key: course
      - name: cloud
        valueFrom:
          configMapKeyRef:
            name: course-config
            key: cloud
      